### ISSUE TITLE
willDestroy is not bound to `this`

### ISSUE THREAD

**Issue by christophersansone** [runspired/rate-limit-computed#2]
I am using `Ember.computed.debounce` on an `Ember.ArrayProxy`.  When calling `destroy()`, it fails with the following:

```
ember.debug.js:36702 Uncaught TypeError: Cannot read property '_teardownArrangedContent' of undefined
```

Upon tracing, it looks like the call to `_super()` on line 46 has a context of `undefined`.  Calling `_super.apply(this)` fixes the issue.

Happy to make a PR.

**Comment by runspired** [comment]
👍
